// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about-us": {
    params: {};
  };
  "/call-for-papers": {
    params: {};
  };
  "/important-dates": {
    params: {};
  };
  "/committees": {
    params: {};
  };
  "/registration": {
    params: {};
  };
  "/registration/form": {
    params: {};
  };
  "/guidelines": {
    params: {};
  };
  "/sponsors": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about-us" | "/call-for-papers" | "/important-dates" | "/committees" | "/registration" | "/registration/form" | "/guidelines" | "/sponsors" | "/contact-us" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about-us";
  };
  "routes/call-for-papers.tsx": {
    id: "routes/call-for-papers";
    page: "/call-for-papers";
  };
  "routes/important-dates.tsx": {
    id: "routes/important-dates";
    page: "/important-dates";
  };
  "routes/committees.tsx": {
    id: "routes/committees";
    page: "/committees";
  };
  "routes/registration.tsx": {
    id: "routes/registration";
    page: "/registration";
  };
  "routes/registration-form.tsx": {
    id: "routes/registration-form";
    page: "/registration/form";
  };
  "routes/guidelines.tsx": {
    id: "routes/guidelines";
    page: "/guidelines";
  };
  "routes/sponsors.tsx": {
    id: "routes/sponsors";
    page: "/sponsors";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact-us";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/call-for-papers": typeof import("./app/routes/call-for-papers.tsx");
  "routes/important-dates": typeof import("./app/routes/important-dates.tsx");
  "routes/committees": typeof import("./app/routes/committees.tsx");
  "routes/registration": typeof import("./app/routes/registration.tsx");
  "routes/registration-form": typeof import("./app/routes/registration-form.tsx");
  "routes/guidelines": typeof import("./app/routes/guidelines.tsx");
  "routes/sponsors": typeof import("./app/routes/sponsors.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};